# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 paths:
   include:
     - worker/*

resources:
- repo: self

variables:

  # So, Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '54db0fff-b4f2-43e5-9a16-58d1efeddf2c'
  imageRepository: 'votingapplication'
  containerRegistry: 'rahulazureregistry26032024.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/worker/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  #vmImageName: 'ubuntu-latest'
pool:
  name: 'azurepool26032024' 
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build the Image
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'worker/Dockerfile'
        tags: '$(tag)'

- stage: Push
  displayName: Push
  jobs:
  - job: Push
    displayName: Push the Image
    steps:
    - task: Docker@2
      displayName: Push and push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'
