# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 paths:
   include:
     - vote/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'df058aff-9f41-4b7d-a0a7-d906978b19fe'
  imageRepository: 'votingapplication'
  containerRegistry: 'rahulazureregistry26032024.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/vote/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  #vmImageName: 'ubuntu-latest'
pool:
  name: 'azurepool26032024'

stages:
- stage: Build
  displayName: Build the Image
  jobs:
  - job: Build
    displayName: Build the Image
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'vote/Dockerfile'
        tags: '$(tag)'
- stage: Push
  displayName: Push the Image
  jobs:
  - job: Push
    displayName: Push the Image
    steps:
    - task: Docker@2
      displayName:  Push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'
